In [ ]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf

In [ ]:
x=tf.constant(4.)
x

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [ ]:
x=tf.constant([[2,3,4],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros((4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
tf.eye(7)

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.random.normal((3,3),mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.06046724, -0.6399798 ,  0.4780073 ],
       [ 1.073225  ,  0.6162671 ,  0.80582017],
       [-0.648966  ,  0.19520153, -0.64089143]], dtype=float32)>

In [ ]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
tf.random.uniform((5,10),minval=3,maxval=9)

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.1279206, 4.269305 , 6.6095138, 8.187999 , 3.6564252, 8.921804 ,
        3.9294798, 4.2778316, 7.132122 , 8.9797   ],
       [3.5065992, 7.6493526, 3.908929 , 4.6283493, 6.641383 , 4.63853  ,
        4.2126884, 7.525731 , 3.4979067, 4.7923117],
       [3.2505376, 5.0114737, 7.2270603, 7.6300287, 6.5004773, 6.760424 ,
        4.432171 , 7.4901934, 7.528637 , 3.5598614],
       [7.847719 , 6.974581 , 7.236187 , 3.7173486, 6.5581408, 5.149239 ,
        4.137039 , 7.3438816, 7.788993 , 3.7906916],
       [3.8294384, 3.349127 , 8.492271 , 3.2571394, 3.1456647, 4.1897182,
        6.9809055, 3.617629 , 6.9677277, 6.855793 ]], dtype=float32)>

In [ ]:
x=tf.range(start=1,limit=10,delta=2)

In [ ]:
tf.cast(x,dtype=tf.float32)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 3., 5., 7., 9.], dtype=float32)>

In [ ]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
x+y
tf.add(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [ ]:
tf.subtract(x,y)
x-y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [ ]:
tf.divide(x,y)
x/y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [ ]:
tf.multiply(x,y)
x*y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [ ]:
z=tf.tensordot(x,y,axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [ ]:
x**5

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

In [ ]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
tf.matmul(x,y)
x@y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.9996814 ,  0.35324842,  0.11022322, -1.8071277 ],
       [ 0.3189839 , -2.2301989 , -0.44757482, -0.8597795 ]],
      dtype=float32)>

In [ ]:
x=tf.constant([0,1,1,2,3,1,2,3])
x[:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [ ]:
x[1:]

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [ ]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
x[::2]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 3, 2], dtype=int32)>

In [ ]:
x[::-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 2, 1, 3, 2, 1, 1, 0], dtype=int32)>

In [ ]:
x=tf.constant([[1,2],
             [3,4],
             [5,6]])

In [ ]:
x[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
x[0:2,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
x=tf.range(9)
x=tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
tf.transpose(x,perm=[1,0])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>